---
jobs:
- name: build-jekyll
  public: true
  plan:
  - get: repository
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/gh-pages}
      inputs: 
        - name: repository
      outputs: 
        - name: site
      run:
        path: sh
        args:
        - -exc
        - |
           cd repository && jekyll build
           cp -r _site ../site && cd ../site
           git init && git config --global user.email "nobody@special.praqma"
           git config --global user.name "praqma" && git add .
           git commit -m "updated gist"
           
  - put: gist
    params: {repository: site}

resources: 
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-workshop.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: gist
  type: git 
  source: 
    uri: git@gist.github.com:e2e59ea5596c9042e1fb0e57467d7711.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}
