---
jobs:
- name: build-jekyll
  public: true
  plan:
  - get: repository
    trigger: true
  - get: gist
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/gh-pages}
      inputs: 
        - name: repository
        - name: gist
      outputs: 
        - name: site
      run:
        path: sh
        args:
        - -exc
        - |
           git clone gist site
           cd repository && jekyll build && cp _site/* ../site && cd ../site
           git config --global user.email "nobody@special.praqma"
           git config --global user.name "praqma" && git add .
           git commit -m "updated gist"
  - put: gist
    params: 
      repository: site

- name: test-site
  public: true
  plan: 
  - get: repository
    passed: [build-jekyll]
  - task: curl-site
    config: 
      platform: linux
      image_resource: 
        type: docker-image
        source: 
          repository: praqma/gh-pages
      run: 
        path: sh
        args: 
        - -exc
        - |
          apt-get install -y curl
          curl https://sharor.github.io/concourse-workshop





resources: 
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-workshop.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: gist
  type: git 
  source: 
    uri: git@gist.github.com:4b2015849c31bfb860c6a021ba9ed63a.git
    branch: master
    private_key: {{concourse-token}}
